version: "3"

services:
  mysql:
    image: mysql:latest
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: unix
      MYSQL_DATABASE: eword
      MYSQL_PASSWORD: unix
    ports:
      - 3306:3306
    volumes:
      - .docker/mysql:/var/lib/mysql
